### ISSUE TITLE
https - not update sensor

### ISSUE THREAD

**Issue by Corinake** [pergolafabio/Hikvision-SDK-Addon#1]
Hi, i use https because i need SmartThings implemetation.
If I use HTTP works perfectly:

Door unlocked, trying to update: sensor.hikvision_door
Unlocked by: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
Door not closed

If I use HTTPS does not work:

Door unlocked, trying to update: sensor.hikvision_door
Sensor updating failed
Unlocked by: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

I change the 'url_states' to http or https.
I don't use both for HA.

**Comment by pergolafabio** [comment]
yeah, script is based to updates sensors in HA :-)

you need to fork it, and remove all sensor related stuff if you want to use it for your own

**Comment by Corinake** [comment]
But I need sensors to update when Open Door even if I use the site with HTTPS. The logs appears not to update: "Sensor Updating Failed". We have also made an automation Light a bulb when the door opens but does not work with HTTPS, only with HTTP.
It is any chance to make it work?

**Comment by pergolafabio** [comment]
yes, the scripts updates a sensor in HA, if that sensor doesnt excist, it failes.... its build for HA purposes

if you want rest calls then change script

**Comment by Corinake** [comment]
I followed your instructions for installing in HA. 
I created the template sensors in Yaml Configuration.
The sensor work but only for HA without SSL.
If I activate SSL HA runs with HTTPS: // and then sensors no longer work for this script.
Now i use NGINX proxy addon with Duckdns addon in HA to use https from internet and http from local ip. And sensors work.

**Comment by pergolafabio** [comment]
ahh, i maybe know why
probably before you were using https on local IP right? i think then the curl fails because it cant verify the certficate

**Comment by Corinake** [comment]
> ahh, i maybe know why probably before you were using https on local IP right? i think then the curl fails because it cant verify the certficate

yes you right, i was try https in lan/local. the problem may be with the certificate

**Comment by pergolafabio** [comment]
Yeah, gonna close for now
