### ISSUE TITLE
[FR] Add support for door unlocking

### ISSUE THREAD

**Issue by grimpy** [pergolafabio/Hikvision-SDK-Addon#2]
See: https://github.com/laszlojakab/hikvision-intercom-python-demo/pull/4

it would be interesting if you would be willing to support this through your addon

**Comment by pergolafabio** [comment]
hi, thats indeed interesting, was already looking at sending stuff to the add-on

**Comment by pergolafabio** [comment]
and how do you call it from HA?

**Comment by pergolafabio** [comment]
You can make a PR for it?

How come the normal ISAPi command doesn't work for you? What device do you have?

**Comment by grimpy** [comment]
The entire ISAPI is not available on the device the port is closed and I can't enable it via ivms it says 'not supported' or something like it. I have [DS-KV8102-IM](https://www.hikvision.com/hk/products/Video-Intercom-Products/IP-Series/Pro-Series/DS-KV8102-IM/)

I won't have time for a PR anytime soon but might consider it in the future

**Comment by pergolafabio** [comment]
ah ok, didnt know port 80 was closed...
firmware update doesnt help?

**Comment by grimpy** [comment]
Nope, latest firmware is from 2019 and hikvision has discontinued the device and stopped any kind of support, this is the reason I was very ingested in seeing some development through the sdk.

**Comment by pergolafabio** [comment]
Cool, I will have also a look at it later, maybe usefull to send other commands too

**Comment by pergolafabio** [comment]
Hey, just a question, if i make that door py file part of the add-on, how are you going to trigger it from HA? since it runs in another docker?

**Comment by grimpy** [comment]
Good question, I don't know much about HA addons tbh, originally when I saw your repo I thought it was like an entity source that runs inside the HA process, after closer look I noticed it runs as a seperate process and triggers updates to HA via an api...

So I'm not sure how to go from here, one option would be is to make some kind of rpc/api and call it from HA.

At the moment I just placed it as a script on my host and defined it as a script inside my configuration.yaml as such
```
shell_command:
  unlock_door: chroot /host-root python3 /opt/hik/hik_unlock_door.py
```
> Note:  I run ha in a docker container and /host-root is my host it's filesystem mounted through docker -v option

**Comment by pergolafabio** [comment]
yes, thats indeed a possible solution, i will make it part of the addon, so you can test it.. will do it later

i had to create an add-on, because the SDK from hikvision is limited to specific OS only, like debian/ubuntu

it doesnt run on alpine , otherwise it was pretty easy

**Comment by pergolafabio** [comment]
Hi, i added the files and that class
can you try it? i'm not home, i made the IP/user/pass as variable, so you need to pass it as arguments like:

python3 hik_unlock_door.py IP USERNAME PASSWORD

**Comment by pergolafabio** [comment]
i think you need to uninstall/reinstall addon, otherwise it doesnt copy over the new file

**Comment by grimpy** [comment]
I'll have a look at it this evening, thanks

**Comment by pergolafabio** [comment]
Hey, i tested it, the command works :-), thnx for this addition
just question, i tried it from the add-on, by accessing it, see below

But tested with chroot, how does that work? We need a shell command to fire  a python file inside another container :-)

![image](https://user-images.githubusercontent.com/43251136/157035829-86dc56aa-8912-423c-aead-0bfb70a27dda.png)

**Comment by pergolafabio** [comment]
ok , this command does work from a shell command:

`docker exec -it addon_a53439b8_hikvision_sdk bash -c "python3 hik_unlock_door.py 192.168.0.70 admin password"`

**Comment by grimpy** [comment]
In the meanwhile I had a quick look at what you've been up to. I think the problem here is that the ha container does not have a docker binary (client) nor access to the docker control socket.

I'm actually currently using HA in standalone container which does not support these kind of addons. How are you running HA?

For me i could use your container image as such since it creates a predictable execution environment.

**Comment by pergolafabio** [comment]
i run HassOS :-)  , the easy way

something like this should work, looking for right command:


```
service: hassio.addon_stdin
data:
  addon: addon_a53439b8_hikvision_sdk
  input: "python3 hik_unlock_door.py 192.168.0.70 admin xxx"
```

**Comment by pergolafabio** [comment]
what is that docker binary client? sorry , new to me :-)

first time i created an addon , so its not perfect :-)

**Comment by grimpy** [comment]
the `docker` binary actually is a client who communicates with `dockerd` the daemon. So what I meant is that you need atleast the `docker` binary with access to the dockerd be it through tcp socker or unix socket.

Meanwhile I looked a the hassio.addon_stdin service: (https://www.home-assistant.io/integrations/hassio/#service-hassioaddon_stdin)

From the description I feel it writes data to the main process of your container it's stdin to communicate with it.
This mean you could from your main process read sys.stdin and execute commands.

so you could for instance have a thread of something similar do
```
for line sys.stdin:
      if line.strip() == "unlock":
           call_unlock_method()
```

eliminating the need for a second process and executing processes through docker.
atleast that's from my understanding of the doc

**Comment by pergolafabio** [comment]
that stdin looks maybe the best way then? i think most usefull for everyone?

**Comment by pergolafabio** [comment]
then we dont need to pass those arguments also, it can be read from the addon options

**Comment by grimpy** [comment]
Yes I think so indeed

**Comment by pergolafabio** [comment]
do you have time to test it?

**Comment by grimpy** [comment]
I actually can't test it as I'm not running HA in a way addons are supported, I didnt realize that at the time I opened this FR though

**Comment by pergolafabio** [comment]
no problem :-)

**Comment by pergolafabio** [comment]
the hik_unlock_door.py works

if i do this as a service, that uses the SSH addon, it should work, but it doenst do anything , strange

i tried using a shell script, where the python command is in
ordirectly using that docker exec command

both command dont do anything

if i run the same command from SSH addon, then it works

```
service: hassio.addon_stdin
data:
  addon: a0d7b954_ssh
  #input: "sh /config/python_scripts/open_door_sdk.sh"
  input: "docker exec -it addon_a53439b8_hikvision_sdk bash -c 'python3 hik_unlock_door.py 192.168.0.70 admin XXXX'"
```

**Comment by pergolafabio** [comment]
ah, wait , seems the service is removed , seeing rls notes

https://github.com/hassio-addons/repository/blob/9d08973517f1e7cb2808e79a8518cefad859a463/ssh/CHANGELOG.md

**Comment by pergolafabio** [comment]
asked community :-)

https://community.home-assistant.io/t/replacement-for-this-service-hassio-addon-stdin/399824

**Comment by grimpy** [comment]
Oh I didnt notice you where refering to the 'input' service and I was refering to another called stdin. If you want I can attempt a PR using the stdin service but I won't be able to full test it.

**Comment by grimpy** [comment]
Yeah so I'm not very much awake or paying enough attention it seems seems this 'input' and 'stdin' are one and the same...

I created a PR with my implementation (untested) https://github.com/pergolafabio/Hikvision-SDK-Addon/pull/3 but if this method is going to be removed or already removed then it's pointless anyway :( they really should add a note in the documentation about that :)

Also you might wonna link this issue in your community post so maybe people can advise with alternative solutions

**Comment by pergolafabio** [comment]
:-)

Cool, will have a look later... Don't think the service is going to removed... Only the option in the SSH addon

**Comment by grimpy** [comment]
I haven't used the forum so I don't have a user there (yet)

**Comment by pergolafabio** [comment]
ah ok

**Comment by pergolafabio** [comment]
added in 2.0 :-)
