### ISSUE TITLE
Подскажите как правильно подключить?

### ISSUE THREAD

**Issue by TokarevSergey** [pergolafabio/Hikvision-SDK-Addon#4]
Добрый день. У меня Hikvision DS-KV6113WTE1. Homeassistant установлен на Oracle VM VirtualBox по инструкции. Я пытаюсь установить Hikvision-SDK-Addon по вашей инструкции и у меня не получается.
1. Подскажите пожалуйста мне нужно отдельно поставить на компьютер какие-то файлы Hikvision-SDK? Если да то какие?
2. Какой ip адрес должен быть в строке "http://localhost:8123/api/states/",? Спасибо.

**Comment by pergolafabio** [comment]
Hi , English please, this is an add-on, you can add it as a custom repository.. then the IP address is localhost, since addon runs on same HA instance

**Comment by TokarevSergey** [comment]
Good afternoon. I have Hikvision DS-KV6113WTE1. Homeassistant installed on Oracle VM VirtualBox according to instructions. I'm trying to install Hikvision-SDK-Addon according to your instructions and I can't.

Can you please tell me if I need to separately install some Hikvision-SDK files on my computer? If so, which ones?
What ip address should be in the line "http://localhost:8123/api/states/",? Thanks.

**Comment by TokarevSergey** [comment]
Can you please tell me if I need to separately install some Hikvision-SDK files on my computer? If so, which ones?

**Comment by pergolafabio** [comment]
no, no need to install anything seperate, its an add-on

**Comment by TokarevSergey** [comment]
Then I don't understand why it doesn't work for me. Does the doorbell need to be adjusted? I have the latest firmware.

**Comment by pergolafabio** [comment]
no, show me the log of your output on the running addon

**Comment by TokarevSergey** [comment]
Excuse me. Everything worked thanks.

**Comment by pergolafabio** [comment]
ah ok :-)
